/* Classic script: shared global bindings. Load order is defined in index.html. */

// Original index.html:407
function startCombat(cfg){pendingCombat={...cfg,hp:cfg.hp,maxHp:cfg.hp,guarding:false,round:1};system(`${cfg.name}와 전투가 시작되었습니다.`,'bad');render()}

// Original index.html:408
function playerDamage(base,skillKey='sword'){const weapon=hasItem('sword')?8:hasItem('knife')?3:0;return Math.max(1,Math.round(base+stat('str')*.16+skill(skillKey)*2+weapon-pendingCombat.def+rollInt(-3,4)))}

// Original index.html:409
function enemyTurn(){if(!pendingCombat)return;const e=pendingCombat;let hit=e.accuracy+rollInt(-15,15)-state.derived.evasion;if(hit>=38){let dmg=Math.max(1,Math.round(e.atk-state.derived.def*.45+rollInt(-2,3)));if(e.guarding)dmg=Math.ceil(dmg*.6);if(pendingCombat.guarding)dmg=Math.ceil(dmg*.52);const fearLoss=e.fear?Math.max(0,Math.round(e.fear*(1-(resistance('fear')||0)/100))):0;modRes({hp:-dmg,spirit:-fearLoss});if(e.fear&&fearLoss>0&&rng()<.07)gainResistance('fear',1,'공포 속에서도 전투를 버텼다',false);addLog(`${e.name}의 공격: 생명력 -${dmg}${fearLoss?` / 정신력 -${fearLoss}`:''}`)}else addLog(`${e.name}의 공격을 피했다.`);pendingCombat.guarding=false;if(state.res.hp<=0){pendingCombat=null;go('death');return}pendingCombat.round++}

// Original index.html:410
function combatAction(type){if(!pendingCombat)return;const e=pendingCombat;clearSystem();if(type==='attack'){if(state.res.stamina<7){system('기력이 부족합니다.','bad');return}modRes({stamina:-7});const k=hasItem('sword')?'sword':'unarmed';const dmg=playerDamage(4,k);e.hp-=dmg;gainSkill(k,1);addLog(`${e.name}에게 ${dmg} 피해`)}else if(type==='heavy'){if(state.res.stamina<16){system('기력이 부족합니다.','bad');return}modRes({stamina:-16});const r=check({stat:'str',skill:hasItem('sword')?'sword':'athletics',diff:63,label:'강공',silent:true});const dmg=r.ok?playerDamage(10,hasItem('sword')?'sword':'unarmed'):playerDamage(1,hasItem('sword')?'sword':'unarmed');e.hp-=dmg;system(r.ok?`강공이 적중해 ${dmg} 피해를 주었습니다.`:`균형이 무너져 ${dmg} 피해밖에 주지 못했습니다.`,r.ok?'good':'bad')}else if(type==='guard'){if(state.res.stamina<5){system('기력이 부족합니다.','bad');return}modRes({stamina:-5});pendingCombat.guarding=true;gainSkill('guard',1);addLog('방어 자세를 취했다.')}else if(type==='recover'){const gain=Math.max(8,Math.round(state.max.stamina*.14));modRes({stamina:gain,spirit:1});pendingCombat.guarding=true;addLog(`숨을 고르며 기력 +${gain}`)}else if(type==='observe'){const r=check({stat:'wis',skill:'observation',diff:58,label:'상대의 움직임 읽기'});if(r.ok){e.accuracy-=6;e.def=Math.max(0,e.def-2);modRes({spirit:2});addLog('상대의 습관을 읽었다.')}}else if(type==='resonance'){if(state.res.mana<10){system('마력이 부족합니다.','bad');return}const top=Object.entries(state.resonance).sort((a,b)=>b[1]-a[1])[0];if(top[1]<8){system('붙잡을 만큼 강한 공명이 없습니다.','bad');return}modRes({mana:-10,spirit:-4});state.stability=clamp(state.stability-3,0,100);let dmg=Math.max(3,Math.round(top[1]*.25+stat('wis')*.08+rollInt(0,5)));e.hp-=dmg;addLog(`${RES_NAMES[top[0]]}의 공명으로 ${dmg} 피해`);if(state.resonanceAwareness<1)state.resonanceAwareness=1}else if(type==='flee'){const r=check({stat:'dex',skill:'athletics',diff:e.speed||58,label:'도주'});if(r.ok){const next=e.fleeTo||'after_fight';pendingCombat=null;go(next);return}}
if(e.hp<=0){const next=e.winTo;state.battles++;state.kills+=e.nonlethal?0:1;pendingCombat=null;modRes({spirit:-1});if(e.onWin)e.onWin(state);go(next);return}enemyTurn();render()}

// Original index.html:412
function renderCombat(){const el=document.getElementById('combat');if(!pendingCombat){el.innerHTML='';return}const e=pendingCombat;const p=Math.max(0,Math.round(e.hp/e.maxHp*100));el.innerHTML=`<div class="combatBox"><div class="combatName">${e.name} <span class="dim">라운드 ${e.round}</span></div><div class="combatBar"><div class="combatFill" style="width:${p}%"></div></div><div class="dim" style="font-size:12px;margin-bottom:10px">상대 상태: ${p>70?'건재':p>40?'상처 입음':p>15?'휘청임':'거의 쓰러짐'} / 내 생명력 ${pct('hp')}% / 기력 ${pct('stamina')}%</div><div class="combatActions"><button onclick="combatAction('attack')">기본 공격<small>기력 7</small></button><button onclick="combatAction('heavy')">강공격<small>기력 16 / 힘 판정</small></button><button onclick="combatAction('guard')">방어<small>기력 5 / 받는 피해 감소</small></button><button onclick="combatAction('recover')">숨을 고른다<small>기력 회복 / 이번 공격 피해 감소</small></button><button onclick="combatAction('observe')">움직임을 읽는다<small>지혜 + 관찰</small></button><button onclick="combatAction('resonance')">공명을 끌어낸다<small>마력 10 / 안정도 위험</small></button><button onclick="combatAction('flee')">도주한다<small>민첩 + 운동</small></button></div></div>`}
