/* Classic script: shared global bindings. Load order is defined in index.html. */

// Original index.html:3620
function registerDepartureScenes(){
scenes.intro={title:'당신이 원래 있던 곳을 떠나는 이유',location:s=>departureInfo11()[0],onEnter:s=>{ensureV11();if(!hasFlag('1.1 출발점')){flag('1.1 출발점');lifeRecord('출발',`${state.origin}의 삶에서 평소 자리를 떠날 이유가 생겼다.`)}},text:s=>{const [place,problem,meaning]=departureInfo11();return `<span class="leadDrop">사건보다 먼저, 삶이 있었다.</span>\n\n당신은 <b>${state.species}, ${state.origin}</b>이다. ${state.originDesc}\n\n<div class="departureBox"><b>${place}</b><br>${problem}</div>\n${meaning}\n\n지금 이 순간 당신은 세계의 중심이 아니다. 오래된 전쟁도, 중앙 지하의 왕도, 엘프의 노래도 대부분 당신과 상관없는 먼 이야기다. 다만 오늘의 선택이 그 거리부터 바꾸기 시작한다.${chaosWhisper()?`\n\n${chaosWhisper()}`:''}`},choices:s=>[
 choice('원래 맡은 일과 생계부터 해결하러 간다.','v11_route_livelihood',{do:s=>{s.departure.reason='생계와 의무';bumpThread('society',6);lifeRecord('선택','이상한 소문보다 원래 맡은 일과 생계를 먼저 택했다.')}}),
 choice('평소와 다른 흔적부터 확인한다.','v11_route_signs',{do:s=>{s.departure.reason='이상 징후';bumpThread('oldroad',7);bumpThread('under',3);lifeRecord('선택','평범하지 않은 흔적을 따라가 보기로 했다.')}}),
 choice('사람들이 무엇을 두려워하는지부터 듣는다.','v11_route_people',{do:s=>{s.departure.reason='사람과 소문';bumpThread('fever',5);bumpThread('society',4);lifeRecord('선택','사람들의 말과 표정을 먼저 확인하기로 했다.')}}),
 choice('오늘은 움직이지 않고 상황을 더 본다.','v11_departure_delay',{do:s=>{s.departure.reason='지연';modRes({spirit:2});advance(2,0);state.city.panic+=2;lifeRecord('선택','당장 움직이지 않고 상황이 변하는 것을 지켜봤다.')}})
]};

scenes.v11_route_livelihood={title:'먹고사는 길',location:'변경도시로 이어지는 길',onEnter:s=>{advance(0,35);modRes({stamina:-4});s.departure.route='livelihood'},text:s=>`길 위에서 만나는 사람들은 같은 방향으로 가면서도 이유가 다르다. 품삯, 세금, 약재, 편지, 수리할 물건.\n\n변경도시는 모험가가 모이는 장소라기보다 주변 수십 마을의 하루가 모이는 시장이다. 그래서 길 하나가 막히면 물가부터 오르고, 사람 하나가 사라지면 그 사람 몫의 일이 다른 사람에게 넘어간다.\n\n오늘은 북문으로 들어와야 할 수레가 유난히 적다.`,choices:[choice('도시에 들어가 내가 하려던 일부터 한다.','v11_arrival',{do:s=>bumpThread('society',4)}),choice('길가 수레와 마부들에게 북문 사정을 묻는다.','v11_route_people',{do:s=>{gainSkill('persuasion',1);bumpThread('fever',2)}})]};

scenes.v11_route_signs={title:'흔적은 말을 하지 않는다',location:'변경도시 바깥의 오래된 길',onEnter:s=>{advance(0,30);modRes({stamina:-5});s.departure.route='signs'},text:s=>`평소와 다른 것은 하나뿐이면 우연일 수 있다. 문제는 오늘 아침부터 작은 이상이 여러 개 겹친다는 점이다.\n\n물 빠진 도랑 아래의 미지근한 바람. 짐승 발자국이 갑자기 끊기는 자리. 두드린 뒤 한 박자 늦게 울리는 도로석. 북쪽에서 내려온 사람들의 검은 기침 자국.\n\n어느 하나도 아직 답은 아니다. 그러나 모두 오래된 길과 변경도시 북쪽을 향한다.`,choices:[choice('표지석과 지반부터 살피며 도시 쪽으로 간다.','v11_arrival',{do:s=>{bumpThread('oldroad',5);if(skill('observation')>=2)knowSuspicion('도시 바깥의 여러 이상 징후가 오래된 북방로 주변에 겹친다.')}}),choice('사람이 사는 곳으로 돌아가 증언과 비교한다.','v11_route_people',{do:s=>bumpThread('society',2)})]};

scenes.v11_route_people={title:'사람은 사실보다 먼저 두려워한다',location:'변경도시 외곽 쉼터',onEnter:s=>{advance(0,25);s.departure.route='people'},text:s=>`쉼터에는 서로 모르는 사람들이 같은 소문을 조금씩 다르게 말한다.\n\n누군가는 북쪽 농가에 열병이 돈다고 하고, 누군가는 공동묘지 흙이 내려앉았다고 한다. 상인은 마부가 사라졌다고 하고, 아이는 밤에 숲에서 사람이 걸어왔다고 한다.\n\n같은 사건인지, 사람들이 불안을 한데 묶고 있는 것인지는 아직 알 수 없다.`,choices:[choice('환자와 구휼 수레가 향한 북문 쪽으로 간다.','v11_arrival',{do:s=>{bumpThread('fever',7);knowSuspicion('북문 열병, 실종, 지반 이상이 같은 시기에 겹치고 있다.')}}),choice('장터에서 실제 가격과 출입 기록부터 확인한다.','v11_arrival',{do:s=>{bumpThread('society',6);gainSkill('trade',1)}})]};

scenes.v11_departure_delay={title:'움직이지 않는 동안에도',location:s=>departureInfo11()[0],onEnter:s=>{advance(2,0);state.city.infection+=2;state.world.roadSafety=clamp(state.world.roadSafety-2,0,100);scheduleConsequence('v11_delay_echo',1,{})},text:s=>`당신이 움직이지 않는 동안에도 다른 사람들은 움직인다. 수레는 다른 길을 택하고, 환자는 성당으로 옮겨지고, 경비대는 북문 장부에 새로운 이름을 적는다.\n\n정오가 가까워질 무렵, 처음 들었던 소문 가운데 하나가 확인된다. 북쪽에서 돌아오지 않은 사람이 실제로 있다.\n\n아무것도 하지 않는 선택도 시간을 쓴다.`,choices:[choice('이제 변경도시로 향한다.','v11_arrival',{do:s=>{bumpThread('society',2);bumpThread('fever',2)}})]};

scenes.v11_delay_echo={title:'하루 늦게 돌아온 소문',location:'중앙 장터',text:s=>`${encounterBadge11('v11_delay_echo')}당신이 전날 지켜보기만 했던 사이, 북문 실종 이야기는 장터 전체에 퍼졌다. 사실은 한 사람이었지만 소문 속에서는 셋이 되었다.\n\n시간을 두면 진실이 선명해지는 일도 있다. 반대로 빈자리를 소문이 먼저 채우는 일도 있다.`,choices:[choice('사실과 소문을 따로 적어둔다.',s=>s.random.returnTo||'day1_hub',{do:s=>{knowFact('북문 실종자는 적어도 한 명 실제로 확인되었다.');knowSuspicion('장터에서는 실종자 수가 과장되어 퍼지고 있다.');bumpThread('society',3)},noEncounter:true})]};

scenes.v11_arrival={title:'변경도시에는 한 개의 입구만 있는 것이 아니다',location:'서부대륙 변경도시 외곽',onEnter:s=>{ensureV11();s.departure.arrived=true;flag('랜덤인카운터 해금');lifeRecord('이동','서부 변경도시에 도착했다.')},text:s=>`성벽이 보인다. 그러나 당신이 무엇을 먼저 보는지는 살아온 삶에 따라 다르다.\n\n상인은 줄어든 수레 수를 보고, 사냥꾼은 성문 가까이까지 내려온 새 발자국을 본다. 성당 사람은 구휼 수레를 보고, 경비 경험이 있는 사람은 창 위에 묻은 진흙과 교대 인원을 본다. 엘프는 인간의 시선과 북방 억양을 먼저 듣고, 동부 출신은 낯선 행정 절차와 익숙하지 않은 평화를 함께 본다.\n\n동문에서는 외지 엘프 하나가 경비병과 말다툼 중이다. 북문에서는 들것이 들어온다. 중앙 장터에서는 소금값이 다시 적힌다. 성벽 밖 오래된 도로석에는 빗물이 고여 있다.\n\n<b>라엔을 만나지 않아도, 폐역참에 가지 않아도, 이 삶은 이미 시작되었다.</b>`,choices:s=>[
 choice('내 일과 숙소부터 정한다.','day1_hub',{do:s=>bumpThread('society',4),review:s=>'당신은 사건의 이름부터 붙이기보다 오늘 머물 곳과 할 일을 먼저 정합니다.'}),
 choice('북문으로 들어오는 환자를 따라간다.','church_sick',{do:s=>bumpThread('fever',9),review:s=>'당신은 소문보다 아픈 사람을 먼저 봅니다. 북문의 이상은 여기서 열병이라는 얼굴을 얻습니다.'}),
 choice('오래된 도로석과 지반을 확인한다.','oldroad_alone',{do:s=>bumpThread('oldroad',9),review:s=>'당신은 사람보다 길에 남은 흔적을 먼저 따라갑니다. 폐역참은 라엔의 사연이 아니라 오래된 교역망의 문제로 처음 모습을 드러냅니다.'}),
 choice('동문의 말다툼을 보러 간다.','intro_laen',{do:s=>{bumpThread('society',3);bumpThread('oldroad',2)},review:s=>'당신은 동문의 충돌로 향합니다. 그곳에서 라엔을 만나게 되지만, 그는 당신 삶의 시작점이 아니라 오늘 마주친 여러 사람 가운데 하나입니다.'}),
 choice('가격과 출입 장부를 비교한다.','work_market',{do:s=>bumpThread('society',8),review:s=>'당신은 장터의 숫자를 택합니다. 길이 막히면 전설보다 먼저 가격이 움직입니다.'})
]};
}

// Original index.html:3653
function registerMajorEncounters(){
Object.assign(scenes,{
 enc_jiangshi_scarecrow:{title:'밭을 지키는 시체',location:'남쪽 개간촌 외곽',onEnter:s=>{advance(0,10);bumpThread('society',2)},text:s=>`${encounterBadge11('enc_jiangshi_scarecrow')}밭 한가운데 허수아비가 서 있다. 가까이 가면 천 아래 손가락 관절이 사람처럼 굽어 있다.\n\n농부는 죽은 사람을 세워둔 것이 아니라며 화를 낸다. “동부식 관절 인형”을 돈 주고 샀다고 한다. 그런데 부적의 먹선은 ${state.originKey==='human_east_jiangshi'?'당신 집안에서 쓰던 오래된 강시 제어식과 너무 닮았다.':'단순한 장식이라고 보기엔 지나치게 규칙적이다.'}\n\n문제는 인형이 어젯밤 밭 끝까지 걸어갔다가 돌아왔다는 증언이다.`,choices:[choice('부적과 관절을 조사한다.',s=>s.random.returnTo,{do:s=>{const r=check({stat:'int',skill:'arcana',diff:62,label:'강시식 판별'});if(r.ok){knowFact('개간촌의 허수아비에는 동부 강시술 계통의 제어식이 쓰였다.');bumpThread('under',5);scheduleConsequence('enc_jiangshi_scarecrow_echo',2)}advance(0,20)},noEncounter:true}),choice('농부에게 밤에는 태워버리라고 한다.',s=>s.random.returnTo,{do:s=>{publicDeed({'factions.farmers':1},'움직이는 허수아비를 태우라고 경고했다','개간촌 농민들이');advance(0,10)},noEncounter:true}),choice('남의 밭일이다. 지나간다.',s=>s.random.returnTo,{do:s=>ignoreEncounter11('enc_jiangshi_scarecrow',6),noEncounter:true})]},
 enc_jiangshi_scarecrow_echo:{title:'허수아비가 있던 자리',location:'남쪽 개간촌',text:s=>`이틀 뒤, 허수아비가 있던 자리에는 말뚝만 남아 있다. 태운 흔적은 없다. 밭 가장자리에서 도시 쪽으로 향한 맨발 같은 자국이 시작된다.\n\n강시술의 오래된 기술이 단순한 골동품으로 서부까지 흘러온 것인지, 누군가 목적을 갖고 옮긴 것인지는 아직 모른다.`,choices:[choice('흔적을 기록하고 다음 일을 따른다.',s=>s.random.returnTo||'day1_hub',{do:s=>{knowSuspicion('서부에 유입된 강시술 제어물이 스스로 이동했을 가능성이 있다.');bumpThread('under',7)},noEncounter:true})]},
 enc_golem_tax:{title:'골렘도 통행세를 내야 하는가',location:'남문 검문대',onEnter:s=>advance(0,8),text:s=>`${encounterBadge11('enc_golem_tax')}짐을 끄는 소형 골렘 하나가 남문 앞에 멈췄다. 주인은 장인 길드의 운송 골렘이라며 물건에만 세금을 내면 된다고 주장한다. 경비병은 “스스로 걷는 건 짐승이든 사람이든 통행 인원”이라고 우긴다.\n\n사소해 보이는 말다툼 뒤에는 더 큰 질문이 있다. 골렘이 도구인지, 노동자인지, 누군가의 재산인지. 인간력 30년의 법은 아직 그 질문을 준비하지 못했다.`,choices:[choice('물건이 아니라 운송수단으로 기록하자고 중재한다.',s=>s.random.returnTo,{do:s=>{const r=check({stat:'wis',skill:'persuasion',diff:57,label:'새 규칙 중재'});if(r.ok){modRep('factions','craftsmen',3,'골렘 통행 분쟁을 현실적으로 중재했다');bumpThread('society',3)}advance(0,15)},noEncounter:true}),choice('법에 없으면 일단 사람과 같은 세금을 내게 한다.',s=>s.random.returnTo,{do:s=>{modRep('factions','guard',2,'골렘 통행에 기존 검문 규칙을 적용했다');bumpThread('society',4);advance(0,10)},noEncounter:true}),choice('흥미롭지만 내 일이 아니다.',s=>s.random.returnTo,{do:s=>ignoreEncounter11('enc_golem_tax',4),noEncounter:true})]},
 enc_resonance_debt:{title:'공명으로 갚는 빚',location:'뒷골목 임시 제단',onEnter:s=>advance(0,8),text:s=>`${encounterBadge11('enc_resonance_debt')}골목 끝 작은 제단 앞에서 남자가 손바닥을 돌 위에 대고 있다. 채권자는 돈 대신 “오늘 한 번의 불 공명”을 빚으로 받겠다고 한다.\n\n공명이 신앙과 같지 않다는 걸 아는 사람에게도 이상한 거래다. 몸과 정신에 남는 힘을 화폐처럼 계약하는 관습은 이 도시의 정식 법에도, 교단 규정에도 없다.\n\n${chaosWhisper()}`,choices:[choice('계약 문구를 확인한다.',s=>s.random.returnTo,{do:s=>{gainSkill('arcana',1);knowSuspicion('일부 뒷골목에서 공명 사용 자체를 채무 상환 수단으로 거래한다.');bumpThread('society',4);advance(0,15)},noEncounter:true}),choice('아델이나 경비대에 알린다.',s=>s.random.returnTo,{do:s=>{modRep('factions','church',2,'불법 공명 채무 거래를 알렸다');bumpThread('society',5);advance(0,10)},noEncounter:true}),choice('계약 당사자들 일이다.',s=>s.random.returnTo,{do:s=>ignoreEncounter11('enc_resonance_debt',6),noEncounter:true})]},
 enc_mithril_knock:{title:'문이 없는 곳의 노크',location:'오래된 배수로 옆',onEnter:s=>{advance(0,6);modRes({spirit:-3})},text:s=>`${encounterBadge11('enc_mithril_knock')}벽 너머에서 세 번 두드리는 소리가 난다. 일정한 간격. 잠시 뒤 두 번. 다시 세 번.\n\n배수로 지도상 이 벽 뒤에는 공간이 없다. 그런데 드워프식 금속 감각이나 높은 역사 지식이 있다면, 아주 먼 중앙에서 전해진 <b>미스릴 도어</b> 이야기의 박자와 비슷하다는 생각이 스친다.\n\n문제는 중앙대륙이 여기서 너무 멀다는 점이다.`,choices:[choice('같은 박자로 벽을 두드려본다.',s=>s.random.returnTo,{do:s=>{const r=check({stat:'wis',skill:'arcana',diff:68,label:'응답 공명'});if(r.ok){modChaos(4,'공간이 없는 벽 너머에서 응답이 돌아왔다');knowSuspicion('미스릴 도어와 유사한 공명 패턴이 변경도시 지하에서도 나타난다.');bumpThread('under',10)}advance(0,10)},noEncounter:true}),choice('위치만 기록하고 물러난다.',s=>s.random.returnTo,{do:s=>{knowSuspicion('지도상 공간이 없는 배수로 벽 너머에서 규칙적인 노크가 들렸다.');bumpThread('under',4)},noEncounter:true}),choice('배수관 소리로 치고 지나간다.',s=>s.random.returnTo,{do:s=>ignoreEncounter11('enc_mithril_knock',8),noEncounter:true})]}
});
}
